# Generated by Django 5.1.1 on 2024-09-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_peticion', models.BigIntegerField()),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Tipo_De_Documento', models.CharField(max_length=50)),
                ('Numero_Documento', models.BigIntegerField()),
                ('Celular', models.CharField(max_length=20)),
                ('Correo', models.EmailField(max_length=254)),
                ('Servicio', models.CharField(max_length=100)),
            ],
        ),
    ]
