# Generated by Django 5.1.1 on 2024-09-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_rename_usuario_consulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='id',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='id_peticion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
