# Generated by Django 5.1.1 on 2024-09-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_rename_numero_documento_consulta_numero_de_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='Numero_De_Documento',
            field=models.CharField(max_length=50),
        ),
    ]
