# Generated by Django 5.1.1 on 2024-09-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0005_alter_consulta_numero_de_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='Numero_De_Documento',
            field=models.BigIntegerField(),
        ),
    ]
